<?php

use Illuminate\Database\Seeder;

class TicketSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$tickets = [
			['projection_id' => 1,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 2,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 3,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 4,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 5,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 6,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 7,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 8,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 9,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 10,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 11,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 12,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 13,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 14,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 15,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 16,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 17,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 18,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 19,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 20,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 21,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 22,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 23,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 24,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 25,
			'user_id' => NULL,
			'row' => 10,
			'column' => 10,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],


			['projection_id' => 1,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 2,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 3,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 4,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 5,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 6,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 7,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 8,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 9,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 10,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 11,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 12,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 13,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 14,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 15,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 16,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 17,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 18,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 19,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 20,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 21,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 22,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 23,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 24,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 25,
			'user_id' => NULL,
			'row' => 1,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],


			['projection_id' => 1,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 2,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 3,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 4,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 5,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 6,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 7,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 8,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 9,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 10,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 11,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 12,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 13,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 14,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 15,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 16,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 17,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 18,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 19,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 20,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 21,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 22,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 23,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 24,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 25,
			'user_id' => NULL,
			'row' => 3,
			'column' => 3,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],


			['projection_id' => 1,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 2,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 3,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 4,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 5,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 6,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 7,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 8,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 9,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 10,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 11,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 12,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 13,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 14,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 15,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 16,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 17,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 18,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 19,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 20,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 21,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 22,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 23,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 24,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 25,
			'user_id' => NULL,
			'row' => 6,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],


			['projection_id' => 1,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 2,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 3,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 4,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 5,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 6,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 7,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 8,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 9,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 10,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 11,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 12,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 13,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 14,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 15,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 16,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 17,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 18,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 19,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 20,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 21,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 22,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 23,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 24,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 25,
			'user_id' => NULL,
			'row' => 9,
			'column' => 7,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],


			['projection_id' => 1,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 2,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 3,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 4,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 5,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 6,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 7,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 8,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 9,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 10,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 11,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 12,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 13,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 14,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 15,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 16,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 17,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 18,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 19,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 20,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 21,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 22,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 23,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 24,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 25,
			'user_id' => NULL,
			'row' => 4,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],


			['projection_id' => 1,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 2,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 3,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 4,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 5,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 6,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 7,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 8,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 9,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 10,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 11,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 12,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 13,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 14,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 15,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 16,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 17,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 18,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 19,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 20,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 21,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 22,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 23,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 24,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 25,
			'user_id' => NULL,
			'row' => 6,
			'column' => 1,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],


			['projection_id' => 1,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 2,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 3,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 4,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 5,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 6,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 7,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 8,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 9,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 10,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 11,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 12,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 13,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 14,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 15,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 16,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 17,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 18,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 19,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 20,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 21,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 22,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 23,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 24,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 25,
			'user_id' => NULL,
			'row' => 1,
			'column' => 9,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],


			['projection_id' => 1,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 2,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 3,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 4,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 5,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 6,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 7,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 8,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 9,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 10,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 11,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 12,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 13,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 14,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 15,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 16,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 17,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 18,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 19,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 20,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 21,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 22,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 23,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 24,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 25,
			'user_id' => NULL,
			'row' => 5,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],


			['projection_id' => 1,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 2,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 3,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 4,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 5,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 6,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 7,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 8,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 9,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 10,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 11,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 12,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 13,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 14,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 15,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 16,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 17,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 18,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 19,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 20,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 21,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 22,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 23,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 24,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],
			['projection_id' => 25,
			'user_id' => NULL,
			'row' => 4,
			'column' => 2,
			'is_paid' => true,
			'token' => NULL,
			'admin_lock' => false,
			],

		];

		foreach ($tickets as $each) {
			DB::table('tickets')->insert($each);        	
		}
	}
}
